### PR TITLE
Controllers and Views

### PR DESCRIPTION
**Pull request by HansZizold**
##CONTROLLERS AND VIEWS
- For the four wireframes specified, the logic for displaying the views was created and tested using:
  - Routes (only the required routes)
  - Controllers and actions
  - View files with plain HTML

[Complete Requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Setup_Controllers_project_v1_1.md)

Happy review!!

### CODE REVIEW

**Review by Reem-lab — COMMENTED** [review]
Hi @HansZizold, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't has a professional README file since Microverse changes the template so I recommend to update it to the new template ✅💯✨🔥[README NEW TEMPLATE](https://github.com/microverseinc/readme-template) and please remove microverse and put the project logo or your own logo 💯✨

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by HansZizold** [comment]
@Reem-lab,
I updated the Readme File according to the template received. 
Thank you!!!

**Review by Reem-lab — COMMENTED** [review]
Hi @HansZizold, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't has a professional README file since you are missing a lot if sections from the updated README that I send in the previous review and the table of content it is very important to so please add it and add all the missing sections to be able to review your project 💯✨🔥🙏🏻

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by HansZizold** [comment]
@Reem-lab, sorry. I think the readme is OK now.
Please check.

Hans

**Review by julie-ify — APPROVED** [review]
Hi @HansZizold,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
