### PR TITLE
Processing Data

### PR DESCRIPTION
**Pull request by HansZizold**
### PROCESSING DATA IN MODELS

- Model classes were created according to the ERD diagram
- Associations between models were set up
- Test data was inserted according to the instructions and CRUD methods tested
- Custom methods were created according to the instructions

Happy review!!

### CODE REVIEW

**Review by t-yanick — APPROVED** [review]
Hi @HansZizold , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive PR
:heavy_check_mark: Excellent use of Rails Active Callbacks

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by t-yanick** [comment]
- [ ] Please remove the Microverse logo before merging the PR. I missed that, if not I would have invalidated your PR. Always remove the Logo from all your future ReadMe and actually ensure that your ReadMe is descriptive.

**Comment by HansZizold** [comment]
> * [ ]  Please remove the Microverse logo before merging the PR. I missed that, if not I would have invalidated your PR. Always remove the Logo from all your future ReadMe and actually ensure that your ReadMe is descriptive.

@t-yanick, thank you very much for your observation. I am proceeding as suggested.

**Comment by HansZizold** [comment]
@t-yanick, thank you very much for your observation. I am proceeding as suggested.

Regards.

**Pull request merged**
